version: '3'
services: 
  authorization-server:
    image: felipedspereira/authorization-server:latest
    container_name: authorization-server
    ports:
      - "8000:8000"
    networks:
      - oauth2-network
    depends_on: 
      - "mysql"
    entrypoint: ./wait-for-it.sh -t 120 mysql:3306 -- java -jar app.jar
  
  resource-server:
    image: felipedspereira/resource-server:latest
    container_name: resource-server
    ports:
      - "9000:9000"
    networks:
      - oauth2-network
    depends_on: 
      - "mysql"
    entrypoint: ./wait-for-it.sh -t 120 mysql:3306 -- java -jar app.jar
      
  mysql:
    build: 
      dockerfile: mysql.dockerfile
      context: .
    image: felipedspereira/mysql-oauth2-example
    container_name: mysql-oauth2-example
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks: 
      - oauth2-network
              
networks:
  oauth2-network:
    driver: bridge
