version: '3'
services: 
  api:
    image: felipedspereira/authorization-server:latest
    container_name: authorization-server
    ports:
      - "8000:8000"
    networks:
      - oauth2-network
    depends_on: 
      - "mysql"
    entrypoint: ./wait-for-it.sh -t 120 mysql:3306 -- java -jar app.jar
      
  mysql:
    build: 
      dockerfile: mysql.dockerfile
      context: ./src/main/resources/docker/
    image: felipedspereira/mysql-authorization-server
    container_name: mysql-authorization-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: authorization_server
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: oauth2
    networks: 
      - oauth2-network
              
networks:
  oauth2-network:
    driver: bridge
